//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CapaPresentacion.ServiceUsuarios {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="UsuarioBE", Namespace="http://schemas.datacontract.org/2004/07/CapaEntidades")]
    [System.SerializableAttribute()]
    public partial class UsuarioBE : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime Us_fech_nacimientoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int Us_idField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string Us_nombreField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string Us_sexoField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime Us_fech_nacimiento {
            get {
                return this.Us_fech_nacimientoField;
            }
            set {
                if ((this.Us_fech_nacimientoField.Equals(value) != true)) {
                    this.Us_fech_nacimientoField = value;
                    this.RaisePropertyChanged("Us_fech_nacimiento");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Us_id {
            get {
                return this.Us_idField;
            }
            set {
                if ((this.Us_idField.Equals(value) != true)) {
                    this.Us_idField = value;
                    this.RaisePropertyChanged("Us_id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Us_nombre {
            get {
                return this.Us_nombreField;
            }
            set {
                if ((object.ReferenceEquals(this.Us_nombreField, value) != true)) {
                    this.Us_nombreField = value;
                    this.RaisePropertyChanged("Us_nombre");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Us_sexo {
            get {
                return this.Us_sexoField;
            }
            set {
                if ((object.ReferenceEquals(this.Us_sexoField, value) != true)) {
                    this.Us_sexoField = value;
                    this.RaisePropertyChanged("Us_sexo");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceUsuarios.IService1")]
    public interface IService1 {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/getSelectUsId", ReplyAction="http://tempuri.org/IService1/getSelectUsIdResponse")]
        CapaPresentacion.ServiceUsuarios.UsuarioBE getSelectUsId(int Us_id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/getSelectUsId", ReplyAction="http://tempuri.org/IService1/getSelectUsIdResponse")]
        System.Threading.Tasks.Task<CapaPresentacion.ServiceUsuarios.UsuarioBE> getSelectUsIdAsync(int Us_id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/setInsertUs", ReplyAction="http://tempuri.org/IService1/setInsertUsResponse")]
        string setInsertUs(CapaPresentacion.ServiceUsuarios.UsuarioBE obj);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/setInsertUs", ReplyAction="http://tempuri.org/IService1/setInsertUsResponse")]
        System.Threading.Tasks.Task<string> setInsertUsAsync(CapaPresentacion.ServiceUsuarios.UsuarioBE obj);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/setUpdateUs", ReplyAction="http://tempuri.org/IService1/setUpdateUsResponse")]
        void setUpdateUs(CapaPresentacion.ServiceUsuarios.UsuarioBE obj);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/setUpdateUs", ReplyAction="http://tempuri.org/IService1/setUpdateUsResponse")]
        System.Threading.Tasks.Task setUpdateUsAsync(CapaPresentacion.ServiceUsuarios.UsuarioBE obj);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/setDeleteUs", ReplyAction="http://tempuri.org/IService1/setDeleteUsResponse")]
        void setDeleteUs(CapaPresentacion.ServiceUsuarios.UsuarioBE obj);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/setDeleteUs", ReplyAction="http://tempuri.org/IService1/setDeleteUsResponse")]
        System.Threading.Tasks.Task setDeleteUsAsync(CapaPresentacion.ServiceUsuarios.UsuarioBE obj);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/getSelectUs", ReplyAction="http://tempuri.org/IService1/getSelectUsResponse")]
        CapaPresentacion.ServiceUsuarios.UsuarioBE[] getSelectUs();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/getSelectUs", ReplyAction="http://tempuri.org/IService1/getSelectUsResponse")]
        System.Threading.Tasks.Task<CapaPresentacion.ServiceUsuarios.UsuarioBE[]> getSelectUsAsync();
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IService1Channel : CapaPresentacion.ServiceUsuarios.IService1, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class Service1Client : System.ServiceModel.ClientBase<CapaPresentacion.ServiceUsuarios.IService1>, CapaPresentacion.ServiceUsuarios.IService1 {
        
        public Service1Client() {
        }
        
        public Service1Client(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public Service1Client(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Service1Client(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Service1Client(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public CapaPresentacion.ServiceUsuarios.UsuarioBE getSelectUsId(int Us_id) {
            return base.Channel.getSelectUsId(Us_id);
        }
        
        public System.Threading.Tasks.Task<CapaPresentacion.ServiceUsuarios.UsuarioBE> getSelectUsIdAsync(int Us_id) {
            return base.Channel.getSelectUsIdAsync(Us_id);
        }
        
        public string setInsertUs(CapaPresentacion.ServiceUsuarios.UsuarioBE obj) {
            return base.Channel.setInsertUs(obj);
        }
        
        public System.Threading.Tasks.Task<string> setInsertUsAsync(CapaPresentacion.ServiceUsuarios.UsuarioBE obj) {
            return base.Channel.setInsertUsAsync(obj);
        }
        
        public void setUpdateUs(CapaPresentacion.ServiceUsuarios.UsuarioBE obj) {
            base.Channel.setUpdateUs(obj);
        }
        
        public System.Threading.Tasks.Task setUpdateUsAsync(CapaPresentacion.ServiceUsuarios.UsuarioBE obj) {
            return base.Channel.setUpdateUsAsync(obj);
        }
        
        public void setDeleteUs(CapaPresentacion.ServiceUsuarios.UsuarioBE obj) {
            base.Channel.setDeleteUs(obj);
        }
        
        public System.Threading.Tasks.Task setDeleteUsAsync(CapaPresentacion.ServiceUsuarios.UsuarioBE obj) {
            return base.Channel.setDeleteUsAsync(obj);
        }
        
        public CapaPresentacion.ServiceUsuarios.UsuarioBE[] getSelectUs() {
            return base.Channel.getSelectUs();
        }
        
        public System.Threading.Tasks.Task<CapaPresentacion.ServiceUsuarios.UsuarioBE[]> getSelectUsAsync() {
            return base.Channel.getSelectUsAsync();
        }
    }
}
